# Generated by Django 3.2.5 on 2021-07-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
