# Generated by Django 3.2.5 on 2021-07-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranumApp', '0003_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_Habitacion',
            field=models.CharField(max_length=50),
        ),
    ]
