# Generated by Django 3.2.5 on 2021-07-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranumApp', '0004_alter_habitacion_tipo_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='cantidad_personas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
